databases:
  - name: elephant
    plan: free
    databaseName: elephant
    user: elephant

services:
  - type: web
    name: elephant
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: elephant
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
